In [2]:

from sklearn.model_selection import train_test_split
#from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
import pandas as pd
import numpy as np
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Activation, Dropout, Flatten, Dense
import tensorflow as tf
from os import listdir
from PIL import Image
import glob, os
from os import listdir
from os.path import isfile, join
import numpy as np
from pandas import DataFrame
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
# las funciones anteriores. Poner a parte e importar

In [4]:
def resize_image(imagen,size,output=False):
    im = Image.open(imagen)
    rgb_image = RGBA_a_RGB(im)
    im_rgb = rgb_image.resize(size)
    
    if not output:
        return im_rgb 
    onlyfiles = [f for f in listdir(output) if isfile(join(output, f))]
    if image not in onlyfiles:
        im.save(output)
        return im_rgb
    else:
        print("file already exists, continuing to next one") 
        return im_rgb

In [5]:
def RGBA_a_RGB(image1):
    if image1.mode == "RGBA":
        background = Image.new("RGB", image1.size, (255, 255, 255))
        background.paste(image1, mask = image1.split()[3])
        background.save(f"{image1}", "JPEG", quality=100)
        rgb_image = Image.open(f"{image1}")
        return rgb_image
    return image1

In [6]:
def image_to_array(image):
    im_np= np.asarray(image)
    one_line=im_np.ravel()
    return one_line

In [7]:
paths={"black":"INPUT/black/",
      "white":"INPUT/white/",
      "green":"INPUT/green/",
      "red":"INPUT/red/"}
images={}
for color,path in paths.items():
    images[color]=[]
    for im in listdir(path):
        if im.endswith("jpg"):
            #size=(64,64)
            a=resize_image(path+im,(64,64))
            images[color].append(np.asarray(a))
    images[color]=np.array(images[color])

In [8]:
def image_to_array(image):
    im_np= np.asarray(image)
    one_line=im_np.ravel()
    return one_line

In [9]:
X= np.concatenate(list(images.values()),axis=0)
y = np.concatenate([[k]* v.shape[0] for k,v in images.items()])

In [ ]:
# Aqui empieza realmente. Division entre la x y la y para test

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
img_width, img_height = 64, 64
img_rows, img_cols = 64, 64

# Prepare data to feed the NN
num_classes = 4

# Ask keras which format to use depending on used backend and arrange data as expected
if K.image_data_format() == 'channels_first':
    X_train = x_train.reshape(X_train.shape[0], 3, img_rows, img_cols)
    X_test = x_test.reshape(X_test.shape[0], 3, img_rows, img_cols)
    input_shape = (3, img_width, img_height)
else:
    X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 3)
    X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 3)
    input_shape = (img_width, img_height, 3)

# Incoming data is in uint8. Cast the input data images to be floats in range [0.0-1.0]  
X_train = tf.keras.utils.normalize(X_train,axis=1)
X_test = tf.keras.utils.normalize(X_test,axis=1)
#X_train = X_train.astype('float32') / 255
#X_test = X_test.astype('float32') / 255

print('x_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

x_train shape: (8388, 64, 64, 3)
8388 train samples
2097 test samples


In [12]:
img_width, img_height = 64, 64

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=input_shape))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(tf.keras.layers.Flatten())

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(4))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [51]:
# get dummies funciona pero lo vamos a cambiar asi que lo #comento y queda fuera
y_train=pd.get_dummies(pd.Series(y_train)).to_numpy()

In [52]:
y_test=pd.get_dummies(pd.Series(y_test)).to_numpy()


In [53]:
y_test

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       ...,
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0]], dtype=uint8)

In [54]:
# cambiar el getdummies por el onehotencoder de felipe. then fit_transform
 from sklearn.preprocessing import OneHotEncoder

In [50]:
##### ESPERA ESPERA ESPERA 
# HACER onehotencoder DESPUES de hacer getdummies? tiene sentido?

In [62]:
y= y.reshape(-1, 1)
y

array([['black'],
       ['black'],
       ['black'],
       ...,
       ['red'],
       ['red'],
       ['red']], dtype='<U5')

In [60]:
enc = OneHotEncoder()

In [65]:
enc.fit(y)  

OneHotEncoder()

In [69]:
enc.transform(y).toarray()
# OJO AQUI AQUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
#sto se lo voy a hacer a ytrain ytest para poder pasarselo al modelo

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [71]:
enc.get_feature_names()

array(['x0_black', 'x0_green', 'x0_red', 'x0_white'], dtype=object)

In [73]:
enc.inverse_transform([[0,1,0,0]])

array([['green']], dtype='<U5')

In [13]:
y_train

array(['black', 'black', 'white', ..., 'white', 'red', 'black'],
      dtype='<U5')

In [ ]:
# Hay que utilizar el label encoder para que reconozca los 4 valores
#hay que dropear la primera columna para que no la haga? 

In [19]:
pd.Series(y_train)

0       black
1       black
2       white
3       black
4       white
        ...  
8383    black
8384    black
8385    white
8386      red
8387    black
Length: 8388, dtype: object

In [22]:
#lo intentamos con el label encoder
from sklearn.preprocessing import LabelEncoder 

In [26]:
le=LabelEncoder() 

In [49]:
y_train_le=le.fit_transform(pd.Series(y_train)) 
y_train_le

array([0, 0, 3, ..., 3, 2, 0])

In [ ]:
# el array ahora tiene cada valor por un numero. Y no podia haber nombrado a cada key del diccionario asi?

In [39]:
onehotencoder = OneHotEncoder() 


SyntaxError: invalid syntax (<ipython-input-41-3f2facdaad8b>, line 1)

In [ ]:
#para correr el modelo

In [77]:
batch_size = 100
epochs = 20

model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(X_test, y_test))



Epoch 1/20
84/84 [==============================] - 12s 142ms/step - loss: 0.0298 - accuracy: 0.9812 - val_loss: 0.0261 - val_accuracy: 0.9800
Epoch 2/20
84/84 [==============================] - 13s 151ms/step - loss: 0.0274 - accuracy: 0.9835 - val_loss: 0.0717 - val_accuracy: 0.9471
Epoch 3/20
84/84 [==============================] - 14s 161ms/step - loss: 0.0242 - accuracy: 0.9844 - val_loss: 0.0272 - val_accuracy: 0.9800
Epoch 4/20
84/84 [==============================] - 14s 167ms/step - loss: 0.0261 - accuracy: 0.9846 - val_loss: 0.0326 - val_accuracy: 0.9809
Epoch 5/20
84/84 [==============================] - 14s 166ms/step - loss: 0.0226 - accuracy: 0.9855 - val_loss: 0.0308 - val_accuracy: 0.9800
Epoch 6/20
84/84 [==============================] - 14s 166ms/step - loss: 0.0208 - accuracy: 0.9884 - val_loss: 0.0274 - val_accuracy: 0.9824
Epoch 7/20
84/84 [==============================] - 14s 167ms/step - loss: 0.0222 - accuracy: 0.9865 - val_loss: 0.0256 - val_accuracy: 0.9852

In [78]:
X_test[56].shape
model.predict(np.array([X_test[403]]))

array([[3.3426697e-19, 7.3386260e-17, 1.3422586e-22, 1.0000000e+00]],
      dtype=float32)